version: 1.0.{build}-{branch}

branches:
  only:
    - master

skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/ 

clone_depth: 5

environment:
  matrix:
    - GENERATOR : "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: x64
      CONFIGURATION: Release

install:
- cmd: >-
    @echo off

    echo Downloading CUDA toolkit 10.2

    appveyor DownloadFile https://doc-0s-5g-docs.googleusercontent.com/docs/securesc/vvgta16bhos9ksqju5b8qul1e4jm81so/7tj05ebgauo1o56i04mr40teqi7r7o62/1578816000000/08703414938308480133/08703414938308480133/1VVZKPOHMHMlOQf4qRi3dimQeKpbL43AB?e=download&authuser=0&nonce=0je59lsepnb1q&user=08703414938308480133&hash=v1o62b8vjehhdegt63hkjgaha7rcl9di

    7z x cuda_distro.zip -ocuda

    cd cuda

    echo Installing CUDA toolkit 10.2

    setup.exe -s cublas_10.2 cublas_dev_10.2 cudart_10.2 curand_10.2 curand_dev_10.2 visual_studio_integration_10.2 nvcc_10.2

    if NOT EXIST "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\cudart64_102.dll" (echo "Failed to install CUDA" exit /B 1)

    cd ..

before_build:
  - mkdir build
  - cd build
  - mkdir bin
  - set OUTPUT_DIR=%cd%\bin
  - cmake .. "-G%GENERATOR%"
    



build_script:
  - cmake .. --build .
