version: 1.0.{build}-{branch}

branches:
  only:
    - ci

skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/ 

clone_depth: 5

environment:
  matrix:
    - GENERATOR : "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: x64
      CONFIGURATION: Release 


install:
- cmd: >-
    @echo off

    appveyor DownloadFile http://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda_10.2.89_441.22_win10.exe -FileName cuda_10.2.89_441.22_win10.exe

    cuda_10.2.89_441.22_win10.exe -s nvcc_10.2 cudart_10.2 curand_10.2 curand_dev_10.2 visual_studio_integration_10.2
    
    set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;%PATH%
    
    nvcc -V

    if NOT EXIST "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\cudart64_102.dll" (echo "Failed to install CUDA" exit /B 1)
    
    cd C:\Tools\vcpkg
    
    git pull
    
    .\bootstrap-vcpkg.bat
    
    cd %APPVEYOR_BUILD_FOLDER%
    
cache:
  - c:\tools\vcpkg\installed\
  
before_build:
  - mkdir build
  - cd build
  - mkdir bin
  - set OUTPUT_DIR=%cd%\bin
  - cmake .. "-G%GENERATOR%" -DCMAKE_CUDA_COMPILER=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/bin/nvcc.exe -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
    



build_script:
  - cmake --build .
