version: 1.0.{build}-{branch}

branches:
  only:
    - master

skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/ 

clone_depth: 5

environment:
  matrix:
    - GENERATOR : "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: x64
      CONFIGURATION: Release

build_script:
  - cmake --build .
