version: 1.0.{build}-{branch}

branches:
  only:
    - master

skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/ 
only_commits:
  message: /build/
  
clone_depth: 5

environment:
  matrix:
    - GENERATOR : "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: x64
      CONFIGURATION: Release

install:
    cmd: "@echo off"
    cmd: "echo Downloading CUDA toolkit 10.2"
    cmd: "appveyor DownloadFile  [link to custom CUDA distribution]"
    cmd: "7z x cuda_distro.zip -ocuda"
    cmd: "cd cuda"
    cmd: "echo Installing CUDA toolkit 9"
    cmd: "setup.exe -s cublas_10.2 cublas_dev_10.2 cudart_10.2 curand_10.2 curand_dev_10.2 visual_studio_integration_10.2 nvcc_10.2"
    cmd: "if NOT EXIST "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\cudart64_102.dll" (echo "Failed to install CUDA" exit /B 1)"
    cmd: "cd .."

build_script:
  - cmake --build .
