version: 1.0.{build}-{branch}

branches:
  only:
    - ci

skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/ 

clone_depth: 5

environment:
  matrix:
    - GENERATOR : "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: x64
      CONFIGURATION: Release 

install:
- cmd: >-
    @echo off

    appveyor DownloadFile https://www.dropbox.com/s/1xhpg0m6u9mvi1d/cuda_distro.7z?dl=1

    7z x cuda_distro.7z -ocuda

    cd cuda

    setup.exe -s cublas_10.2 cublas_dev_10.2 cudart_10.2 curand_10.2 curand_dev_10.2 visual_studio_integration_10.2 nvcc_10.2

    if NOT EXIST "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\cudart64_102.dll" (echo "Failed to install CUDA" exit /B 1)
    
    cd ..

before_build:
  - mkdir build
  - cd build
  - mkdir bin
  - set OUTPUT_DIR=%cd%\bin
  - cmake .. "-G%GENERATOR%" "-DCMAKE_CUDA_COMPILER=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe"
    



build_script:
  - cmake .. --build .
